version: '3.8'

services:
  web:
    build:
      context: ./todomvc
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - db
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    networks:
      - app-network

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
