name: Deploy on push

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove package-lock.json
        run: rm -f package-lock.json

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '10.x'  # 使用 Node.js 10.x

      - name: Cache npm modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install
        working-directory: ./todomvc

      - name: Run build
        run: npm run build
        working-directory: ./todomvc

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push todomvc image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/todomvc ./todomvc
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/todomvc

      - name: Build and push html image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/html ./html
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/html

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/todomvc
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/html
            docker stop todomvc || true
            docker stop html || true
            docker rm todomvc || true
            docker rm html || true
            docker run -d --name todomvc -p 8081:8081 ${{ secrets.DOCKER_HUB_USERNAME }}/todomvc
            docker run -d --name html -p 8080:80 ${{ secrets.DOCKER_HUB_USERNAME }}/html
